### ISSUE TITLE
Concurrency issue with flush

### ISSUE THREAD

**Issue by halfhp** [LachlanMcKee/timber-junit-rule#7]
There appears to be a race condition in `BufferedJUnitTimberTree.flushLogs`.  If `mLogMessageBuffer` is mutated by another thread while flushLogs is running, a `ConcurrentModificationException` is thrown.

Unfortunately I don't have a precise example to repro but the defect seems straight forward and should be quite easy to fix by adding some synchronization.

Cheers!

**Comment by LachlanMcKee** [comment]
Thanks @halfhp, I'll look into it :)

**Comment by LachlanMcKee** [comment]
Hi @halfhp this should be fixed as of `1.0.1` let me know if there are any issues with the change!
